# Generated by Django 6.1.1 on 2026-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prazo",
            fields=[
                ("id_prazo", models.AutoField(primary_key=True, serialize=False)),
                ("dias_de_atraso", models.CharField(max_length=5)),
                ("dias_suspensao", models.CharField(max_length=5)),
            ],
        ),
    ]
