# Generated by Django 6.1.1 on 2026-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                ("id_livro", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=60)),
                ("autor", models.CharField(max_length=60)),
            ],
        ),
    ]
