# Generated by Django 6.1.1 on 2026-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="livros/"),
        ),
    ]
