# Generated by Django 6.1.1 on 2026-09-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_livro_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="genero",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="livro",
            name="sinopse",
            field=models.TextField(blank=True, null=True),
        ),
    ]
