# Generated by Django 6.1.1 on 2026-09-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_livro_genero_livro_sinopse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="genero",
        ),
    ]
