# Generated by Django 6.1.1 on 2026-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("senha", models.CharField(max_length=15)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
    ]
