# Generated by Django 6.1.1 on 2026-09-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exemplares", "0001_initial"),
        ("prazo", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                ("previsao_devolucao", models.DateField()),
                (
                    "exemplar",
                    models.ForeignKey(
                        db_column="ID_exemplar",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exemplares.exemplar",
                    ),
                ),
                (
                    "prazo",
                    models.ForeignKey(
                        db_column="ID_prazo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prazo.prazo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="ID_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
