# Generated by Django 6.1.1 on 2026-09-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exemplar",
            fields=[
                ("id_exemplar", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=60)),
                ("autor", models.CharField(max_length=60)),
                (
                    "livro",
                    models.ForeignKey(
                        db_column="ID_livro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livros.livro",
                    ),
                ),
            ],
        ),
    ]
