# Generated by Django 6.1.1 on 2026-09-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exemplares", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("id_reserva", models.AutoField(primary_key=True, serialize=False)),
                ("data_reserva", models.DateField()),
                ("status", models.CharField(max_length=15)),
                (
                    "exemplar",
                    models.ForeignKey(
                        db_column="ID_exemplar",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exemplares.exemplar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="ID_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
